### ISSUE TITLE
Job post form

### ISSUE THREAD

**Issue by Shammioamk** [Product-Design-Implementation-Group-4/User_Application_Frontend#18]

**Comment by Shammioamk** [comment]
Working in job post form.

**Comment by Shammioamk** [comment]
Implemented Job post functionality.
Design UI for job post page.

**Comment by PankajChakrabarty** [comment]
location and helper type need to be updated after job post

**Comment by MdJunayedurRahman** [comment]
If someone needs it, they should contact us. We will update them.

**Comment by Shammioamk** [comment]
All done.
