### ISSUE TITLE
User Login & Registration

### ISSUE THREAD

**Issue by MdJunayedurRahman** [Product-Design-Implementation-Group-4/User_Application_Frontend#3]

**Comment by Shammioamk** [comment]
- [x] Initialize React project.
- [x] Install necessary dependencies (React Router, Firebase/Auth0 for OAuth, etc.)
- [x] Build Login Page UI
- [x] Build Registration Page UI
- [x] Implement Form Validation
- [x] Implement Email Login & Registration Functionality
- [x] Implement Google Login Integration
- [x] Implement Facebook Login Integration

**Comment by Shammioamk** [comment]
complete user login & registration with email, Google, and Facebook integration, including UI and form validation.

**Comment by PankajChakrabarty** [comment]
- [x] Sign Up Function (Features Updated " Verification of password, Add profile image")
- [x] Responsive feature added for desktop and mobile view

**Comment by Shammioamk** [comment]
- [x] Changed the Navbar layout design.
- [x] Implemented account delectation feature.

**Comment by PankajChakrabarty** [comment]
All functions tested. Working properly. Alerts are also woking fine
