### ISSUE TITLE
Develop User Form with Checkboxes, Dropdowns, and Picture Upload

### ISSUE THREAD

**Issue by MdJunayedurRahman** [Product-Design-Implementation-Group-4/User_Application_Frontend#4]
Description:
"Create a frontend form that allows users to fill in their information with the following fields: text inputs, checkboxes, dropdown options, and picture upload. Implement functionality to save the submitted data to the database."

Acceptance Criteria:
- The form includes required fields with text inputs, checkboxes, dropdown options, and picture uploads.
- Form validation is implemented (e.g., required fields, correct formats).
-  Data is saved to the database upon submission.
-  User receives feedback upon successful form submission or if there are errors.

**Comment by MdJunayedurRahman** [comment]
- [x] Developed basic form with Name, Phone, email, location,  and helper type.

**Comment by MdJunayedurRahman** [comment]
- [x] Copleted Frontend part for User Form

**Comment by PankajChakrabarty** [comment]
The form for UI is working accurately

**Comment by MdJunayedurRahman** [comment]
All functions tested. Working properly.
