### ISSUE TITLE
User Registration with default profile picture

### ISSUE THREAD

**Issue by MdJunayedurRahman** [Product-Design-Implementation-Group-4/User_Application_Frontend#5]
Add default profile picture for users without one

**Comment by MdJunayedurRahman** [comment]
- [x] When users register without uploading a profile picture, the system should automatically assign a default profile picture.

**Comment by MdJunayedurRahman** [comment]
Completed the feature.

**Comment by PankajChakrabarty** [comment]
tested, The function working perfectly
