### ISSUE TITLE
User Form Submission Functionality.

### ISSUE THREAD

**Issue by MdJunayedurRahman** [Product-Design-Implementation-Group-4/User_Application_Frontend#7]

**Comment by PankajChakrabarty** [comment]
Create a frontend form that allows users to fill
their information with the following fields:
 text inputs,
  checkboxes,
   dropdown options,
   scroll and search dropdown,
    and picture upload(single and/or multiple). Implement functionality to save the submitted data to the database.

**Comment by MdJunayedurRahman** [comment]
All functions tested. Working properly.
