### ISSUE TITLE
User Profile page View

### ISSUE THREAD

**Issue by MdJunayedurRahman** [Product-Design-Implementation-Group-4/User_Application_Frontend#8]

**Comment by Shammioamk** [comment]
Design and implement a user-friendly, visually appealing profile page with a focus on proper alignment, consistency, and responsive image display. Ensure the uploaded images are uniformly styled and centered while maintaining compatibility across different screen sizes.

**Comment by MdJunayedurRahman** [comment]
All functions tested. Working properly.

**Comment by PankajChakrabarty** [comment]
Feature needed, after upload the image cant preview the image

**Comment by MdJunayedurRahman** [comment]
We will add this feature in the future.
