### ISSUE TITLE
User profile page edit

### ISSUE THREAD

**Issue by Shammioamk** [Product-Design-Implementation-Group-4/User_Application_Frontend#9]

**Comment by MdJunayedurRahman** [comment]
UI design for user profile edit page.
Implemented functionality that allows user to edit their profile successfully.

**Comment by MdJunayedurRahman** [comment]
Me and Shammi implemented it together and all functions were tested. Working properly.

**Comment by PankajChakrabarty** [comment]
it doesnt updated automatically or rerouted after save changes button. Manually need to go to home page

**Comment by Shammioamk** [comment]
Now it is working. All functions tested.
